### ISSUE TITLE
The letter K cannot be used in waypoint names

### ISSUE THREAD

**Issue by Bigity** [Summit60/DCS-Hercules-TheWay-patch-v1.01#1]
This patch for the DCS herc mod, will not use the letter K (or k) in waypoint names.  The letter simply is skipped over.

I removed the default binding for k (kneeboard glance) but the issue remained.  It works on other aircraft using TheWay.

**Comment by Summit60** [comment]
Should be fixed now, simple typo! Not able to test atm so let me know if you can!

**Comment by Summit60** [comment]
Excuse the repeated open close, still learning github lmao

**Comment by Bigity** [comment]
No worries, appreciate the quick response!

**Comment by Summit60** [comment]
> No worries, appreciate the quick response!

Was just Glad it was on my external script and not on "the way" side. Much quicker that way
